# Generated by Django 5.1.2 on 2024-11-13 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(help_text="Localização do estoque (ex: 'Armazém A')", max_length=100, verbose_name='Localização')),
                ('setor', models.CharField(help_text="Setor ou divisão do estoque (ex: 'Eletrônicos')", max_length=100, verbose_name='Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do produto (ex: 'Smartphone')", max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(help_text='Descrição detalhada do produto', verbose_name='Descrição')),
                ('quantidade_estoque', models.PositiveIntegerField(help_text='Número total de unidades disponíveis', verbose_name='Quantidade em Estoque')),
                ('preco', models.DecimalField(decimal_places=2, help_text="Preço do produto em reais (ex: '199.99')", max_digits=10, verbose_name='Preço')),
                ('data_adicao', models.DateField(auto_now_add=True, help_text='Data em que o produto foi adicionado', verbose_name='Data de Adição')),
                ('estoque', models.ForeignKey(help_text='Estoque em que o produto está armazenado', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app_estoque.estoque', verbose_name='Estoque')),
            ],
        ),
    ]
